# Generated by Django 2.1.4 on 2018-12-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact', models.TextField(max_length=32)),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField(max_length=255)),
                ('added_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField(max_length=255)),
                ('contact', models.TextField(max_length=32)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=32)),
                ('weight', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField(max_length=255)),
                ('added_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact', models.TextField(max_length=32)),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField(max_length=255)),
                ('added_date', models.DateTimeField()),
            ],
        ),
    ]
