# Generated by Django 2.1.4 on 2018-12-29 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='added_date',
            field=models.DateTimeField(default=datetime.timezone),
        ),
        migrations.AlterField(
            model_name='patient',
            name='added_date',
            field=models.DateTimeField(default=datetime.timezone),
        ),
        migrations.AlterField(
            model_name='reception',
            name='added_date',
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
