# Generated by Django 2.1.4 on 2018-12-29 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cals', '0002_auto_20181229_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 14, 16, 45, 321149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 14, 16, 45, 348597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reception',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 14, 16, 45, 349595, tzinfo=utc)),
        ),
    ]
