# Generated by Django 2.1.4 on 2019-03-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cals', '0006_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField()),
                ('diet', models.TextField()),
                ('exercise', models.TextField()),
                ('precaution', models.TextField()),
            ],
        ),
    ]
