# Generated by Django 2.1.4 on 2019-03-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cals', '0007_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.TextField()),
                ('prescription', models.TextField()),
                ('BeforeAfter', models.TextField()),
                ('morning', models.TextField()),
                ('afternoon', models.TextField()),
                ('evening', models.TextField()),
                ('days', models.TextField()),
            ],
        ),
    ]
