# Generated by Django 2.1.4 on 2019-03-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cals', '0008_prescriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptions',
            old_name='BeforeAfter',
            new_name='after',
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='before',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
