# Generated by Django 2.1.4 on 2019-03-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cals', '0009_auto_20190315_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.TextField()),
                ('testname', models.TextField()),
                ('normal_range', models.TextField()),
                ('test_found', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
    ]
