# Generated by Django 2.1.4 on 2019-04-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cals', '0010_mtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dep',
            name='rtest',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
